# Generated by Django 5.2.7 on 2025-10-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="date_joined",
        ),
        migrations.AddField(
            model_name="student",
            name="admission_year",
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name="student",
            name="level",
            field=models.CharField(
                choices=[
                    ("100", "100 Level"),
                    ("200", "200 Level"),
                    ("300", "300 Level"),
                    ("400", "400 Level"),
                ],
                max_length=10,
            ),
        ),
    ]
