# Generated by Django 5.2.4 on 2025-12-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("lecturer", "Lecturer"),
                    ("admin", "Admin"),
                ],
                default="admin",
                max_length=20,
            ),
        ),
    ]
