# Generated by Django 5.2.4 on 2025-12-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("lecturer", "Lecturer"),
                    ("admin", "Admin"),
                ],
                max_length=20,
            ),
        ),
    ]
