# Generated by Django 5.2.7 on 2025-12-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_elective",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="offered_level",
            field=models.CharField(
                choices=[
                    ("100", "100 Level"),
                    ("200", "200 Level"),
                    ("300", "300 Level"),
                    ("400", "400 Level"),
                ],
                default="100",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="pass_mark",
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name="course",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True, related_name="required_for", to="academics.course"
            ),
        ),
    ]
