# Generated by Django 5.2.4 on 2025-12-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_course_is_elective_course_offered_level_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="is_elective",
        ),
        migrations.AddField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                choices=[("core", "Core"), ("elective", "Elective")],
                default="core",
                max_length=10,
            ),
        ),
    ]
